# -*- coding: utf-8 -*-
"""app_flask

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buxFlNyeGeA10ozf8aoQ6OvggBIu9lbF

# SEMANA 3
"""

from flask import Flask, jsonify, render_template
import pandas as pd
from logic import normalizar_columnas, limpiar_datos, generar_analisis_estadistico
from schemas import CreditOutputSchema
import os # Import os module to handle file existence

app = Flask(__name__)

# Ruta al archivo (Asegúrate que el nombre coincida con el de tu carpeta)
FILE_PATH_XLSX = "/content/BD_Credit_2025_completo.xlsx"
FILE_PATH_CSV = "/content/BD_Credit_2025_completo.csv" # Keep csv for potential future use or if conversion is needed

@app.route('/')
def home():
    """Endpoint para mostrar el análisis descriptivo (Simulación de HTML)."""
    try:
        # Check if the XLSX file exists, otherwise try CSV
        if os.path.exists(FILE_PATH_XLSX):
            df = pd.read_excel(FILE_PATH_XLSX)
        elif os.path.exists(FILE_PATH_CSV):
            df = pd.read_csv(FILE_PATH_CSV)
        else:
            raise FileNotFoundError("Neither BD_Credit_2025_completo.xlsx nor .csv found.")

        df = normalizar_columnas(df)
        df = limpiar_datos(df)
        stats = generar_analisis_estadistico(df)

        return jsonify({
            "titulo": "Análisis Descriptivo Microcréditos 2025",
            "metricas": stats,
            "mensaje": "Este objeto JSON puede ser consumido por tu archivo HTML"
        })
    except Exception as e:
        return jsonify({"error": str(e)})

@app.route('/clean', methods=['GET'])
def clean_data_endpoint():
    """SEMANA 3: Migración de funciones de limpieza a Endpoint."""
    try:
        # 1. Cargar y procesar
        # Check if the XLSX file exists, otherwise try CSV
        if os.path.exists(FILE_PATH_XLSX):
            df = pd.read_excel(FILE_PATH_XLSX)
        elif os.path.exists(FILE_PATH_CSV):
            df = pd.read_csv(FILE_PATH_CSV)
        else:
            raise FileNotFoundError("Neither BD_Credit_2025_completo.xlsx nor .csv found.")

        df = normalizar_columnas(df)
        df = limpiar_datos(df)

        # 2. Seleccionar solo las columnas que coinciden con el OutputSchema
        columnas_salida = ["customer_id", "cupo_solicitado", "cupo_aprobado", "ratio_aprobacion", "resultado_cobranza"]
        # Ensure all required columns exist before selecting
        available_cols = [col for col in columnas_salida if col in df.columns]
        datos_finales = df[available_cols].head(100).to_dict(orient='records')

        # 3. Validar con Pydantic (opcional pero recomendado)
        # Filter out records that might not fully conform to the schema if columns are missing
        valid_data = []
        for item in datos_finales:
            try:
                valid_data.append(CreditOutputSchema(**item).model_dump())
            except Exception as validation_error:
                print(f"Skipping invalid record: {item} due to {validation_error}")

        return jsonify({
            "status": "success",
            "records_cleaned": len(df),
            "sample": valid_data
        })
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

if __name__ == "__main__":
    # In a Colab environment, use a different approach to run Flask apps directly
    # For local execution, app.run(debug=True, port=5000) is standard.
    # For Colab, you might use ngrok or a similar tool for public exposure
    # or run it in a way that it can be accessed within Colab.
    # For now, we will not run app.run() to avoid blocking the kernel
    # if the intention is to just define the app and modules.
    print("Flask app defined. Run `app.run()` if you want to start the server.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile logic.py
# import pandas as pd
# from datetime import datetime
# 
# def normalizar_columnas(df: pd.DataFrame) -> pd.DataFrame:
#     df.columns = df.columns.str.lower()
#     return df
# 
# def convertir_fecha(df: pd.DataFrame) -> pd.DataFrame:
#     if 'loandate' in df.columns:
#         df['loandate'] = pd.to_datetime(df['loandate'], errors='coerce')
#     return df
# 
# def eliminar_nulos(df: pd.DataFrame) -> pd.DataFrame:
#     return df.dropna()
# 
# def eliminar_duplicados(df: pd.DataFrame) -> pd.DataFrame:
#     return df.drop_duplicates()
# 
# def crear_ratio_aprobacion(df: pd.DataFrame) -> pd.DataFrame:
#     if "cupo_aprobado" in df.columns and "cupo_solicitado" in df.columns:
#         df["ratio_aprobacion"] = df["cupo_aprobado"] / df["cupo_solicitado"].replace(0, pd.NA)
#     return df
# 
# def limpiar_datos(df: pd.DataFrame) -> pd.DataFrame:
#     df = convertir_fecha(df)
#     df = eliminar_nulos(df)
#     df = eliminar_duplicados(df)
#     df = crear_ratio_aprobacion(df)
#     return df
# 
# def generar_analisis_estadistico(df: pd.DataFrame) -> dict:
#     numeric_cols = df.select_dtypes(include=['number']).columns
#     if not numeric_cols.empty:
#         return df[numeric_cols].describe().to_dict()
#     else:
#         return {"message": "No numeric columns for statistical analysis."}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile schemas.py
# from pydantic import BaseModel, Field
# from datetime import datetime
# 
# 
# class CreditInputSchema(BaseModel):
#     customer_id: int = Field(..., example=1082423)
#     loandate: datetime = Field(..., example="2020-05-28")
#     age: float = Field(..., gt=18, example=35)
#     income: float = Field(..., gt=0, example=1500)
#     time_experience: float = Field(..., ge=0, example=5)
#     cupo_solicitado: float = Field(..., gt=0, example=20000)
#     score_1: int = Field(..., ge=0, le=1000)
#     score_2: int = Field(..., ge=0, le=1000)
#     score_3: int = Field(..., ge=0, le=1000)
#     score_4: int = Field(..., ge=0, le=1000)
# 
# 
# class CreditOutputSchema(BaseModel):
#     customer_id: int
#     cupo_solicitado: float
#     cupo_aprobado: float
#     ratio_aprobacion: float
#     resultado_cobranza: str

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import os
from logic import normalizar_columnas, limpiar_datos # Import the necessary functions

# Load the data and process it to define 'df'
FILE_PATH_XLSX = "/content/BD_Credit_2025_completo.xlsx"
df = pd.read_excel(FILE_PATH_XLSX)
df = normalizar_columnas(df)
df = limpiar_datos(df)

# Create the 'static' directory if it doesn't exist
os.makedirs('static', exist_ok=True)

plt.figure(figsize=(10,6))
sns.histplot(df['age'], kde=True, color='blue')
plt.title('Distribución de Edades de Clientes')
plt.savefig('static/distribucion_edad.png')
plt.show() # Display the plot in the output