# -*- coding: utf-8 -*-
"""limpieza

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmHLlD_3mgL4Rj1jE_JMA3X0k_L-4139

Proyecto Fase 1: Seleccionar dataset personal, limpieza básica en Pandas, modularizar limpieza en funciones puras (archivo .py separado).
"""

pip install flask pandas openpyxl



from flask import Flask, render_template
import pandas as pd

app = Flask(__name__)

@app.route('/')
def index():
    # Leemos el Excel
    df = pd.read_excel('BD_Credit_2025_completo.xlsx')

app.logger.warning("Duplicate route definition for / was removed. Check cell jW1k5yhn_TsE for the active home route.")

"""
**Proyecto Fase 1:** Seleccionar dataset personal, limpieza básica en Pandas, modularizar limpieza en funciones puras (archivo .py separado)."""

# --- Contenido para limpieza.py ---
import pandas as pd
import numpy as np

def limpiar_datos_credito(df: pd.DataFrame) -> pd.DataFrame:
    """
    Función pura para limpieza básica de BD_Credit_2025
    """
    # 1. Normalizar nombres de columnas
    df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]

    # 2. Manejo de nulos (basado en tu notebook)
    df = df.dropna(subset=['id_credit']) # ID es vital

    # 3. Conversión de tipos
    if 'loandate' in df.columns:
        df['loandate'] = pd.to_datetime(df['loandate'], errors='coerce')

    # 4. Eliminar duplicados
    df = df.drop_duplicates()

    return df



import pandas as pd

def cargar_datos(ruta: str) -> pd.DataFrame:
    return pd.read_excel(ruta)

def normalizar_columnas(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = df.columns.str.lower()
    return df

def convertir_fecha(df: pd.DataFrame) -> pd.DataFrame:
    df["loandate"] = pd.to_datetime(df["loandate"])
    return df

def eliminar_nulos(df: pd.DataFrame) -> pd.DataFrame:
    return df.dropna()

def eliminar_duplicados(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop_duplicates()

def crear_ratio_aprobacion(df: pd.DataFrame) -> pd.DataFrame:
    df["ratio_aprobacion"] = df["cupo_aprobado"] / df["cupo_solicitado"]
    return df

def ejecutar_pipeline() -> None:
    df = cargar_datos("/content/BD_Credit_2025_completo.xlsx")
    df = normalizar_columnas(df)
    df = convertir_fecha(df)
    df = eliminar_nulos(df)
    df = eliminar_duplicados(df)
    df = crear_ratio_aprobacion(df)

    print(df.head())
    print("Dimensión final:", df.shape)

if __name__ == "__main__":
    ejecutar_pipeline()

"""### ANALISIS DESCRIPTIVO"""

# Cargar datos
df = pd.read_excel("BD_Credit_2025_completo.xlsx")

# Normalizar columnas
df.columns = df.columns.str.lower()

print("Dimensiones del dataset:", df.shape)
df.head()

"""**2️⃣ Calidad de Datos**"""

# Tipos de datos
df.info()

# Valores nulos
nulls = df.isnull().sum().sort_values(ascending=False)
nulls[nulls > 0]

# Porcentaje de nulos
(df.isnull().mean() * 100).sort_values(ascending=False)

# Duplicados
print("Duplicados:", df.duplicated().sum())

"""📊 3️⃣ Estadística Descriptiva General"""

df.describe().T

df.describe(include='all').T

"""📈 4️⃣ Análisis por Variables Clave

🎂 Edad
"""

print("Edad promedio:", df["age"].mean())
print("Edad mínima:", df["age"].min())
print("Edad máxima:", df["age"].max())

import matplotlib.pyplot as plt

df["age"].hist(bins=20)
plt.title("Distribución de Edad")
plt.xlabel("Edad")
plt.ylabel("Frecuencia")
plt.show()

"""💰 Ingreso"""

print("Ingreso promedio:", df["income"].mean())
print("Ingreso mediana:", df["income"].median())

df["income"].hist(bins=20)
plt.title("Distribución de Ingresos")
plt.show()

"""💳 5️⃣ Análisis Crediticio"""

df["ratio_aprobacion"] = df["cupo_aprobado"] / df["cupo_solicitado"]

print("Ratio promedio:", df["ratio_aprobacion"].mean())

df["ratio_aprobacion"].hist(bins=20)
plt.title("Distribución Ratio de Aprobación")
plt.show()

"""**Relación ingreso vs cupo solicitado**"""

plt.scatter(df["income"], df["cupo_solicitado"])
plt.xlabel("Ingreso")
plt.ylabel("Cupo Solicitado")
plt.title("Ingreso vs Cupo Solicitado")
plt.show()

"""**Scores**"""

scores = ["score_1", "score_2", "score_3", "score_4"]
df[scores].describe()

df[scores].boxplot()
plt.title("Distribución Scores")
plt.show()

"""🔗 6️⃣ Matriz de Correlación"""

corr = df.corr(numeric_only=True)
corr

plt.figure(figsize=(10,8))
plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Matriz de Correlación")
plt.show()

"""📊 7️⃣ Segmentación
Por rangos de edad
"""

df["grupo_edad"] = pd.cut(df["age"], bins=[18,25,35,50,70])

df.groupby("grupo_edad")["ratio_aprobacion"].mean()

"""**Por nivel de ingreso**"""

df["grupo_ingreso"] = pd.qcut(df["income"], 4)

df.groupby("grupo_ingreso")["cupo_aprobado"].mean()

"""📈 8️⃣ Detección de Outliers"""

Q1 = df["income"].quantile(0.25)
Q3 = df["income"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["income"] < Q1 - 1.5*IQR) |
              (df["income"] > Q3 + 1.5*IQR)]

print("Cantidad de outliers en ingreso:", len(outliers))

print("Coeficiente de variación ingreso:",
      df["income"].std() / df["income"].mean())

print("Skewness ingreso:", df["income"].skew())
print("Kurtosis ingreso:", df["income"].kurt())