# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQakWl94AyQx7pFhtlFeEJV-tEzT8o8R

# Semana 4:Transición a FastAPI
"""

# --- Contenido para main.py ---
from fastapi import FastAPI, HTTPException
from typing import List
from schemas import CreditInput, CreditOutput
import pandas as pd
from limpieza import limpiar_datos_credito

app = FastAPI(title="API de Créditos 2025")

@app.post("/clean", response_model=List[CreditOutput])
async def clean_data(data: List[CreditInput]):
    # Convertimos lista de Pydantic a DataFrame
    df = pd.DataFrame([item.dict() for item in data])

    # Aplicamos limpieza de Semana 1
    df_cleaned = limpiar_datos_credito(df)

    # Retornamos según el esquema de salida
    return [CreditOutput(id_credit=row['id_credit']) for _, row in df_cleaned.iterrows()]