# -*- coding: utf-8 -*-
"""schemas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1625l_MRznVYLPc8zArGBZL2IwPJLLnNH

# **Semana 2 : Crear esquemas Pydantic para el dataset elegido en Fase 1 (InputSchema y OutputSchema).**
"""

from pydantic import BaseModel, Field
from datetime import datetime


class CreditInputSchema(BaseModel):
    customer_id: int = Field(..., example=1082423)
    loandate: datetime = Field(..., example="2020-05-28")
    age: float = Field(..., gt=18, example=35)
    income: float = Field(..., gt=0, example=1500)
    time_experience: float = Field(..., ge=0, example=5)
    cupo_solicitado: float = Field(..., gt=0, example=20000)
    score_1: int = Field(..., ge=0, le=1000)
    score_2: int = Field(..., ge=0, le=1000)
    score_3: int = Field(..., ge=0, le=1000)
    score_4: int = Field(..., ge=0, le=1000)


class CreditOutputSchema(BaseModel):
    customer_id: int
    cupo_solicitado: float
    cupo_aprobado: float
    ratio_aprobacion: float
    resultado_cobranza: str

from pydantic import BaseModel, Field
from datetime import datetime


class CreditInputSchema(BaseModel):
    customer_id: int = Field(..., example=1082423)
    loandate: datetime = Field(..., example="2020-05-28")
    age: float = Field(..., gt=18, example=35)
    income: float = Field(..., gt=0, example=1500)
    time_experience: float = Field(..., ge=0, example=5)
    cupo_solicitado: float = Field(..., gt=0, example=20000)
    score_1: int = Field(..., ge=0, le=1000)
    score_2: int = Field(..., ge=0, le=1000)
    score_3: int = Field(..., ge=0, le=1000)
    score_4: int = Field(..., ge=0, le=1000)

data = {
    "customer_id": 1082423,
    "loandate": "2020-05-28",
    "age": 30,
    "income": 2000,
    "time_experience": 5,
    "cupo_solicitado": 15000,
    "score_1": 500,
    "score_2": 600,
    "score_3": 650,
    "score_4": 700
}

credit = CreditInputSchema(**data)
print(credit)

"""# Semana 5 Validación Avanzada (Refinar schemas.py)"""

# --- Actualización para schemas.py (Semana 5) ---
from pydantic import Field

class CreditInput(BaseModel):
    id_credit: int = Field(..., gt=0, description="ID único del crédito")
    age: float = Field(..., gt=18, lt=100, description="Edad debe ser entre 18 y 100 años")
    income: float = Field(..., ge=0, description="El ingreso no puede ser negativo")
    cupo_solicitado: float = Field(..., gt=0)